window.PROJECTS = [
  {
    "id": "shield-dojo",
    "title": "Shield Dojo",
    "category": "Games",
    "kind": "Reflex arcade",
    "edition": "Bounce edition v3",
    "description": "An Amiga-inspired karate arcade. Time your shield against bouncing balls and work your way from white belt to Legend.",
    "controls": "Keyboard + touch",
    "file": "artifacts/shield-dojo.html",
    "line1": "SHIELD",
    "line2": "DOJO",
    "year": "1989",
    "number": "01",
    "bytes": 30574
  },
  {
    "id": "albion-transport",
    "title": "Albion Transport",
    "category": "Games",
    "kind": "Transport tycoon",
    "edition": "1950–1959",
    "description": "Build a passenger empire across a fictional Britain, with steam trains, buses, propeller aircraft and up to two rival tycoons.",
    "controls": "Keyboard + touch",
    "file": "artifacts/albion-transport.html",
    "line1": "ALBION",
    "line2": "TRANSPORT",
    "year": "1950",
    "number": "02",
    "bytes": 62042
  },
  {
    "id": "eagle-descent",
    "title": "Eagle: The Final Descent",
    "category": "Space",
    "kind": "Interactive diorama",
    "edition": "Apollo 11",
    "description": "Follow the lunar module from the first computer alarm through the boulder field to touchdown, with a guided timeline and sound.",
    "controls": "3D · WebGL",
    "file": "artifacts/eagle-descent.html",
    "line1": "THE EAGLE",
    "line2": "HAS LANDED",
    "year": "1969",
    "number": "03",
    "bytes": 757006
  },
  {
    "id": "apollo-rollout",
    "title": "Apollo 11: Crawlerway to Sky",
    "category": "Space",
    "kind": "Interactive diorama",
    "edition": "Apollo 11",
    "description": "Travel with the Saturn V from the Vehicle Assembly Building to the launch pad, then follow liftoff through first-stage separation.",
    "controls": "3D · WebGL",
    "file": "artifacts/apollo-rollout.html",
    "line1": "CRAWLERWAY",
    "line2": "TO SKY",
    "year": "1969",
    "number": "04",
    "bytes": 714186
  },
  {
    "id": "anzac-landing",
    "title": "The Anzac Landing",
    "category": "History",
    "kind": "Guided diorama",
    "edition": "25 April 1915",
    "description": "Follow the offshore approach, the landing boats and the first ridges in a source-informed miniature of the Anzac landing.",
    "controls": "3D · WebGL",
    "file": "artifacts/anzac-landing.html",
    "line1": "THE ANZAC",
    "line2": "LANDING",
    "year": "1915",
    "number": "05",
    "bytes": 753742
  },
  {
    "id": "singapore-1942",
    "title": "The Fall of Singapore",
    "category": "History",
    "kind": "Guided diorama",
    "edition": "February 1942",
    "description": "Explore the mainland approach, Singapore, Sentosa and Changi through a guided sequence of the campaign and its aftermath.",
    "controls": "3D · WebGL",
    "file": "artifacts/singapore-1942.html",
    "line1": "SINGAPORE",
    "line2": "FEBRUARY",
    "year": "1942",
    "number": "06",
    "bytes": 767476
  },
  {
    "id": "gallipoli",
    "title": "Gallipoli: A Living Miniature",
    "category": "History",
    "kind": "Interactive diorama",
    "edition": "Campaign sandbox",
    "description": "Explore a fictionalised Gallipoli landscape. Follow units, send supplies and adjust the action across the coast, cliffs and trenches.",
    "controls": "3D · WebGL",
    "file": "artifacts/gallipoli.html",
    "line1": "COAST. CLIFFS.",
    "line2": "TRENCHES.",
    "year": "1915",
    "number": "07",
    "bytes": 742503
  },
  {
    "id": "singapore-local",
    "title": "Singapore, Andrew’s Way",
    "category": "Travel",
    "kind": "3D neighbourhood explorer",
    "edition": "Andrew’s local list · 2026",
    "description": "Watch Changi jets, spot the Merlion and explore a lively voxel Singapore. Twelve places include Andrew’s food picks, Botanic Gardens and Night Safari.",
    "controls": "3D · WebGL",
    "file": "artifacts/singapore-local.html",
    "line1": "SINGAPORE,",
    "line2": "ANDREW’S WAY",
    "year": "2026",
    "number": "08",
    "bytes": 761132
  }
];
