'use strict';
(() => {
const T=THREE,$=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,smooth=t=>t*t*(3-2*t);
const canvas=$('view');let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){renderer=new EverestSoftwareRenderer(canvas,T);$('modeNote').textContent='Simplified 3D · graphics compatibility mode';}
$('info').onclick=()=>{$('notes').showModal();setPlaying(false)};$('closeNotes').onclick=()=>$('notes').close();
if(!renderer)return;
renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene();scene.background=new T.Color('#7194ac');scene.fog=new T.FogExp2('#7194ac',0.00085);
const camera=new T.PerspectiveCamera(47,1,.5,6500);const hemi=new T.HemisphereLight('#cceaff','#384257',2.3);scene.add(hemi);const sun=new T.DirectionalLight('#ffdfb1',3.1);sun.position.set(-350,700,220);scene.add(sun);
let seed=1996;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
const route=[[-235,36.4,275],[-213,55,241],[-177,83,210],[-140,105,170],[-94,135,143],[-47,150,114],[5,183,98],[65,230,72],[94,260,35],[80,279,7],[102,292.6,-26],[65,328,-63],[51,340,-80],[16,374.9,-123],[6,379,-141],[0,384.8,-153]].map(p=>V(...p));
function atRoute(u){u=clamp(u,0,route.length-1);let i=Math.min(route.length-2,Math.floor(u));return route[i].clone().lerp(route[i+1],u-i)}
function routeNear(x,z){let best=1e9,y=0,u=0;for(let i=0;i<route.length-1;i++){const a=route[i],b=route[i+1],dx=b.x-a.x,dz=b.z-a.z,t=clamp(((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz),0,1);const d=Math.hypot(x-a.x-dx*t,z-a.z-dz*t);if(d<best){best=d;y=mix(a.y,b.y,t);u=i+t}}return {d:best,y,u}}
const peaks=[[0,-153,384.8,1.03],[175,63,351.6,1.12],[-128,98,286.1,1.22],[-242,-144,225,1.02],[238,-207,269,1.05],[-330,202,169,1.05],[295,224,176,1.1],[-80,-370,193,1.1]];
function height(x,z){let h=-8;for(const [px,pz,py,slope]of peaks){const dx=x-px,dz=z-pz,d=Math.hypot(dx,dz),a=Math.atan2(dz,dx);const ridge=1+.15*Math.sin(a*3+.7)+.065*Math.cos(a*7);h=Math.max(h,py-d*slope*ridge)}const n=routeNear(x,z);const detail=(Math.sin(x*.12+z*.08)*Math.cos(z*.09-x*.04)*4+Math.sin(x*.045-z*.062)*6);h+=detail*Math.min(1,n.d/14);if(n.d<31)h=mix(h,n.y,smooth(1-n.d/31));h=Math.max(-8,h);return h}
const size=1000,div=220,geom=new T.PlaneGeometry(size,size,div,div);geom.rotateX(-Math.PI/2);const pos=geom.attributes.position;
for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,height(x,z))}geom.computeVertexNormals();
const terr=geom.toNonIndexed(),tp=terr.attributes.position;const colours=[];const snow=new T.Color('#d8e9ee'),ice=new T.Color('#80b6ca'),rock=new T.Color('#65717a'),darkrock=new T.Color('#3f4b58'),yellow=new T.Color('#ac9c73');
const av=V(),bv=V(),cv=V(),norm=V();
for(let i=0;i<tp.count;i+=3){av.fromBufferAttribute(tp,i);bv.fromBufferAttribute(tp,i+1);cv.fromBufferAttribute(tp,i+2);norm.subVectors(bv,av).cross(cv.clone().sub(av)).normalize();const x=(av.x+bv.x+cv.x)/3,z=(av.z+bv.z+cv.z)/3,y=(av.y+bv.y+cv.y)/3,near=routeNear(x,z);let c=snow.clone();if(norm.y<.62)c.copy(darkrock).lerp(rock,rand());else if(norm.y<.79)c.copy(rock).lerp(snow,rand()*.5);if(near.d<24&&near.u<8&&near.u>1)c.copy(ice).lerp(snow,.35+rand()*.4);if(y<65&&near.u<2)c.copy(rock).lerp(snow,rand()*.45);if(y>253&&y<264&&x>50&&z>0)c.copy(yellow);c.multiplyScalar(.9+rand()*.18);for(let k=0;k<3;k++)colours.push(c.r,c.g,c.b)}
terr.setAttribute('color',new T.Float32BufferAttribute(colours,3));const mountain=new T.Mesh(terr,new T.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:true}));scene.add(mountain);geom.dispose();
if(renderer.isSoftware){const low=new T.PlaneGeometry(size,size,85,85);low.rotateX(-Math.PI/2);const p=low.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,height(p.getX(i),p.getZ(i)));low.computeVertexNormals();const lg=low.toNonIndexed(),lp=lg.attributes.position,ln=lg.attributes.normal,lc=[];for(let i=0;i<lp.count;i++){const x=lp.getX(i),z=lp.getZ(i),y=lp.getY(i),r=routeNear(x,z);const col=new T.Color(ln.getY(i)<.76?'#687884':'#d8e9ee');if(r.d<24&&r.u>1&&r.u<8)col.set('#9ed0df');if(y>253&&y<264&&x>50&&z>0)col.set('#ac9c73');lc.push(col.r,col.g,col.b)}lg.setAttribute('color',new T.Float32BufferAttribute(lc,3));mountain.userData.softwareGeometry=lg;low.dispose();}

const mat=(c,other={})=>new T.MeshStandardMaterial({color:c,roughness:.9,...other});
const base=new T.Mesh(new T.BoxGeometry(1000,30,1000),mat('#263947'));base.position.y=-24;scene.add(base);
const foundation=new T.Mesh(new T.BoxGeometry(1004,5,1004),mat('#101f2b'));foundation.position.y=-41;scene.add(foundation);
// Distant relief gives the fly-through a Himalayan horizon without external imagery.
const far=new T.Group();for(let i=0;i<38;i++){const a=i/38*Math.PI*2,r=1050+rand()*380,h=100+rand()*220;const m=new T.Mesh(new T.ConeGeometry(170+rand()*170,h,5+Math.floor(rand()*3)),mat(i%3?'#b3c7d3':'#839eaf'));m.position.set(Math.cos(a)*r,h/2-55,Math.sin(a)*r);m.rotation.y=rand()*6;far.add(m)}scene.add(far);
function lineBetween(a,b,r,color,parent=scene){const d=b.clone().sub(a),mesh=new T.Mesh(new T.CylinderGeometry(r,r,d.length(),5),mat(color));mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(V(0,1,0),d.normalize());parent.add(mesh);return mesh}
// The warm line is a schematic route overlay, not a depiction of continuously fixed rope.
const linePoints=[];for(let u=0;u<15;u+=.025){const p=atRoute(u);p.y=height(p.x,p.z)+1.9;linePoints.push(p)}linePoints.push(route[15].clone().add(V(0,2,0)));
const pathGeom=new T.BufferGeometry().setFromPoints(linePoints);const path=new T.Line(pathGeom,new T.LineBasicMaterial({color:'#ffcf72',transparent:true,opacity:.88}));scene.add(path);
const routeGlow=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(linePoints),650,.42,4,false),new T.MeshBasicMaterial({color:'#f3bc62'}));scene.add(routeGlow);
// Icefall seracs, dark crevasses and ladder crossings.
const seracs=new T.InstancedMesh(new T.BoxGeometry(1,1,1),mat('#c0e8ef',{flatShading:true}),260),dummy=new T.Object3D();
for(let i=0;i<260;i++){const u=.6+rand()*2.65,p=atRoute(u);p.x+=(rand()-.5)*55;p.z+=(rand()-.5)*30;const h=2+rand()*12;dummy.position.set(p.x,height(p.x,p.z)+h*.36,p.z);dummy.rotation.set((rand()-.5)*.32,rand(),(rand()-.5)*.32);dummy.scale.set(2+rand()*6,h,2+rand()*7);dummy.updateMatrix();seracs.setMatrixAt(i,dummy.matrix)}scene.add(seracs);
for(const u of [1.25,1.95,2.55]){const p=atRoute(u);p.y=height(p.x,p.z)+2.5;const gap=new T.Mesh(new T.BoxGeometry(30,.6,3),mat('#163c52'));gap.position.copy(p);scene.add(gap);for(const dx of [-.85,.85])lineBetween(p.clone().add(V(dx,.8,-5)),p.clone().add(V(dx,.8,5)),.11,'#d6d6c4');for(let z=-4.8;z<5;z+=.8)lineBetween(p.clone().add(V(-.85,.8,z)),p.clone().add(V(.85,.8,z)),.1,'#e9e6d4')}
const campNames=['BASE CAMP','CAMP I','CAMP II','CAMP III','CAMP IV · SOUTH COL'];
const camps=[];const tentGeo=new T.SphereGeometry(3.8,8,4,0,Math.PI*2,0,Math.PI/2);const tentMats=[mat('#edac42'),mat('#db6235'),mat('#dfa736')];
for(const [ci,u]of [0,3,5,7,10].entries()){const center=atRoute(u),group=new T.Group();for(let i=0;i<(ci===0?19:ci===4?9:6);i++){const a=i*2.4,rad=ci===0?7+Math.sqrt(i)*6:5+Math.sqrt(i)*5,x=center.x+Math.cos(a)*rad,z=center.z+Math.sin(a)*rad,y=height(x,z)+.5;const tent=new T.Mesh(tentGeo,tentMats[i%3]);tent.position.set(x,y,z);tent.scale.set(1,.7,1.25);group.add(tent);const door=new T.Mesh(new T.PlaneGeometry(2.1,2),mat('#172c38',{side:T.DoubleSide}));door.position.set(x,y+1,z+4.2);group.add(door);lineBetween(V(x,y+4,z),V(x+6,y,z+6),.08,'#e7dac0',group)}camps.push(group);scene.add(group)}
// Summit prayer flags and the old Hillary Step.
const summit=route[15];lineBetween(summit.clone(),summit.clone().add(V(0,12,0)),.18,'#9b9d8b');
const flags=[];for(let i=0;i<17;i++){const f=new T.Mesh(new T.PlaneGeometry(2.3,2),mat(['#d89b42','#cf604f','#729bd4','#e4e4c7','#519b89'][i%5],{side:T.DoubleSide}));f.position.copy(summit).add(V(-18+i*2.1,8-Math.sin(i/16*Math.PI)*3,0));flags.push(f);scene.add(f)}lineBetween(summit.clone().add(V(-18,9,0)),summit.clone().add(V(18,9,0)),.07,'#dac998');
const step=atRoute(14.15);const stepRock=new T.Mesh(new T.BoxGeometry(5.5,7,6),mat('#59616b'));stepRock.position.copy(step).add(V(1,1.8,1));stepRock.rotation.z=.13;scene.add(stepRock);
const labelDefs=[['EVEREST · 8,848 m',15],['BASE CAMP · 5,364 m',0],['CAMP I · ~6,050 m',3],['CAMP II · ~6,500 m',5],['CAMP III · ~7,300 m',7],['SOUTH COL · ~7,926 m',10],['THE BALCONY',12],['SOUTH SUMMIT',13]];
const labels=labelDefs.map(([name,u])=>{const el=document.createElement('div');el.className='map-label';el.textContent=name;$('labels').appendChild(el);return {el,p:atRoute(u).add(V(0,12,0)),u}});
for(const [name,p]of [['LHOTSE · 8,516 m',V(175,365,63)],['NUPTSE · 7,861 m',V(-128,299,98)]]){const el=document.createElement('div');el.className='map-label';el.textContent=name;$('labels').appendChild(el);labels.push({el,p,u:-1})}
const people=[],personGeo=new T.CapsuleGeometry(.7,1.5,2,5),headGeo=new T.SphereGeometry(.54,6,4),lampGeo=new T.SphereGeometry(.25,5,3),bodyMats=['#e66839','#e6bf4c','#459eb7','#d0524c'].map(c=>mat(c));const boots=mat('#172835'),headMat=mat('#d9ceba'),lampMat=new T.MeshBasicMaterial({color:'#fff5c7'});
for(let i=0;i<24;i++){const g=new T.Group();const body=new T.Mesh(personGeo,bodyMats[i%4]);body.position.y=2;g.add(body);const head=new T.Mesh(headGeo,headMat);head.position.y=3.6;g.add(head);const pack=new T.Mesh(new T.BoxGeometry(1.3,1.7,.8),boots);pack.position.set(0,2.2,-.8);g.add(pack);const lamp=new T.Mesh(lampGeo,lampMat);lamp.position.set(0,3.7,.52);g.add(lamp);const legs=[];for(const x of [-.42,.42]){const leg=new T.Mesh(new T.BoxGeometry(.42,1.4,.48),boots);leg.position.set(x,.7,0);g.add(leg);legs.push(leg)}scene.add(g);people.push({g,legs,lamp})}
const beacon=new T.Mesh(new T.SphereGeometry(1.8,12,8),new T.MeshBasicMaterial({color:'#ffda8f'}));scene.add(beacon);
const snowCount=1400,snowPositions=new Float32Array(snowCount*3);for(let i=0;i<snowPositions.length;i++)snowPositions[i]=(rand()-.5)*500;const sg=new T.BufferGeometry();sg.setAttribute('position',new T.BufferAttribute(snowPositions,3));const snowMat=new T.PointsMaterial({color:'#e6f4ff',size:.8,transparent:true,opacity:0,depthWrite:false});const flakes=new T.Points(sg,snowMat);scene.add(flakes);
const starsPos=[];for(let i=0;i<850;i++){const a=rand()*Math.PI*2,r=2400,y=350+rand()*1900;starsPos.push(Math.cos(a)*r,y,Math.sin(a)*r)}const stars=new T.Points(new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(starsPos,3)),new T.PointsMaterial({color:'#dae9ff',size:3,transparent:true,opacity:0,fog:false}));scene.add(stars);
const chapters=[
{title:'The mountain before the storm',when:'EARLIER DAYS · THE APPROACH',phase:'01 / APPROACH TO HIGH CAMP',u:0,dist:710,angle:-.8,lift:.7,day:1,storm:0,text:'From Nepal, the route rises through the Khumbu Icefall and Western Cwm. Weeks of acclimatisation precede the summit push.',note:'A guided miniature · 4 minutes 40 seconds'},
{title:'Through the Khumbu Icefall',when:'EARLIER DAYS · BELOW CAMP I',phase:'01 / APPROACH TO HIGH CAMP',u:1.8,dist:140,angle:-.9,lift:.65,day:1,storm:0,text:'Crevasses split the glacier. Ladders bridge the gaps between moving towers of ice. Sherpa teams establish and maintain the passage.',note:'Ice towers and ladder positions are illustrative.'},
{title:'The Western Cwm',when:'EARLIER DAYS · CAMPS I & II',phase:'01 / APPROACH TO HIGH CAMP',u:4.4,dist:205,angle:-.55,lift:.7,day:1,storm:0,text:'A glacial valley opens between Everest, Lhotse and Nuptse. Camp II lies below the steep wall of the Lhotse Face.',note:'Follow the gold line through the valley.'},
{title:'Up the Lhotse Face',when:'8–9 MAY · CAMP III AND ABOVE',phase:'01 / APPROACH TO HIGH CAMP',u:7.3,dist:175,angle:-1,lift:.62,day:1,storm:0,text:'Fixed ropes lead up blue ice to Camp III. Above it, the Yellow Band and Geneva Spur guard the approach to the South Col.',note:'The tan rock layer marks the Yellow Band.'},
{title:'The last camp',when:'9 MAY · SOUTH COL',phase:'01 / APPROACH TO HIGH CAMP',u:10,dist:150,angle:-1,lift:.7,day:.48,storm:.05,text:'Camp IV occupies the exposed saddle between Everest and Lhotse. The summit still stands roughly 900 metres above.',note:'Route elevations are approximate.'},
{title:'Headlamps into the dark',when:'9–10 MAY · AROUND MIDNIGHT',phase:'02 / THE SUMMIT PUSH',u:10.2,dist:100,angle:-1.1,lift:.55,day:0,storm:0,text:'Rob Hall’s Adventure Consultants and Scott Fischer’s Mountain Madness depart the South Col around midnight.',note:'Climber figures represent a group, not named individuals.'},
{title:'Dawn at the Balcony',when:'10 MAY · EARLY MORNING',phase:'02 / THE SUMMIT PUSH',u:12,dist:118,angle:-1.15,lift:.65,day:.55,storm:0,text:'The route reaches a small resting place on the southeast ridge. Rope work and congestion slow progress.',note:'The amount of delay differs between accounts.'},
{title:'The South Summit',when:'10 MAY · LATE MORNING',phase:'02 / THE SUMMIT PUSH',u:13,dist:125,angle:-1.2,lift:.6,day:1,storm:0,text:'Some climbers turn back. Those continuing face the exposed cornice traverse and the Hillary Step.',note:'The gold line traces the narrow upper ridge.'},
{title:'The Hillary Step',when:'10 MAY · AROUND MIDDAY',phase:'02 / THE SUMMIT PUSH',u:14.1,dist:73,angle:-1.2,lift:.5,day:1,storm:.02,text:'In 1996, the final rock step was a steep obstacle near the summit. Climbers funnel onto fixed ropes.',note:'The pre-2015 landmark is enlarged for visibility.'},
{title:'The highest point',when:'10 MAY · EARLY TO LATE AFTERNOON',phase:'02 / THE SUMMIT PUSH',u:15,dist:110,angle:-.9,lift:.5,day:1,storm:.1,text:'Early climbers summit around 13:00. Others arrive much later, leaving less daylight and oxygen for descent.',note:'8,848 m · the familiar elevation used in 1996.'},
{title:'The storm closes in',when:'10 MAY · LATE AFTERNOON',phase:'03 / DESCENT INTO THE STORM',u:12.8,dist:105,angle:-.8,lift:.55,day:.25,storm:.8,text:'Wind and snow intensify during descent. Exhaustion, limited oxygen and poor visibility compound the danger.',note:'Weather is illustrative, not a meteorological replay.'},
{title:'Lost near the tents',when:'10 MAY · EVENING AND NIGHT',phase:'03 / DESCENT INTO THE STORM',u:10.3,dist:110,angle:-.9,lift:.6,day:0,storm:1,text:'A group becomes stranded near the South Col, unable to find Camp IV in the whiteout.',note:'The camera keeps some visibility so the terrain remains readable.'},
{title:'Rescue in the darkness',when:'11 MAY · OVERNIGHT INTO DAYLIGHT',phase:'04 / RESCUE AND REMEMBRANCE',u:10,dist:150,angle:-1,lift:.65,day:.22,storm:.62,text:'Anatoli Boukreev brings three clients back to camp. Other guides and Sherpa climbers continue rescue efforts. Beck Weathers later returns alive.',note:'Hall remains high on the mountain; attempts to reach him fail.'},
{title:'Eight lives remembered',when:'10–11 MAY 1996',phase:'04 / RESCUE AND REMEMBRANCE',u:10,dist:730,angle:-.8,lift:.68,day:.45,storm:.15,text:'Five climbers died on the south side, and three from the Indo-Tibetan Border Police expedition on the north side.',note:'Open Field notes for their names, sources and differing accounts.'}
];
chapters.forEach((c,i)=>{const o=document.createElement('option');o.value=i;o.textContent=String(i+1).padStart(2,'0')+' · '+c.title;$('chapters').appendChild(o)});
let time=0,playing=false,speed=1,chapter=-1,overview=false,orbit=0,pitch=0,zoom=1,last=performance.now(),labelClock=0,frameCount=0,frameTime=0,night=0,storm=0,needSnap=true;
const focus=V(-15,150,20),targetFocus=V(),desiredCam=V();camera.position.set(-510,620,570);let audio=null,soundOn=false;
function setPlaying(value){playing=value;$('play').textContent=playing?'Ⅱ Pause':time>=280?'↺ Replay':time===0?'▶ Begin ascent':'▶ Resume'}
function jump(i){time=clamp(i,0,chapters.length-1)*20;orbit=0;pitch=0;zoom=1;updateChapter();$('seek').value=time}
function updateChapter(){const i=Math.min(13,Math.floor(time/20));if(i===chapter)return;chapter=i;const c=chapters[i];$('title').textContent=c.title;$('narrative').textContent=c.text;$('when').textContent=c.when;$('note').textContent=c.note;$('phase').textContent=c.phase;$('count').textContent=String(i+1).padStart(2,'0')+' / 14';$('chapters').value=i;if(soundOn&&i>=5&&i<=12)chirp();}
$('play').onclick=()=>{if(time>=280){time=0;needSnap=true}setPlaying(!playing)};$('prev').onclick=()=>jump(chapter-1);$('next').onclick=()=>jump(chapter+1);$('chapters').onchange=e=>jump(+e.target.value);$('seek').oninput=e=>{time=+e.target.value;updateChapter();if(time>=280)setPlaying(false)};$('speed').onchange=e=>speed=+e.target.value;
$('overview').onclick=()=>{overview=!overview;$('overview').setAttribute('aria-pressed',overview);$('overview').textContent=overview?'Follow route':'Route overview';orbit=0;pitch=0;zoom=1;};
$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){$('modeNote').textContent='Open the standalone page for fullscreen.'}};
const pointers=new Map();let lastPinch=0;canvas.addEventListener('pointerdown',e=>{canvas.focus();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);lastPinch=0});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===1){orbit-=(e.clientX-old[0])*.006;pitch=clamp(pitch+(e.clientY-old[1])*.004,-.15,.75)}else{const a=[...pointers.values()];const d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(lastPinch)zoom=clamp(zoom*lastPinch/d,.5,3);lastPinch=d}});for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{pointers.delete(e.pointerId);lastPinch=0});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*Math.exp(e.deltaY*.001),.5,3)},{passive:false});document.addEventListener('keydown',e=>{if($('notes').open||['INPUT','SELECT','BUTTON','A'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();if(time>=280)time=0;setPlaying(!playing)}if(e.code==='ArrowRight'){e.preventDefault();jump(chapter+1)}if(e.code==='ArrowLeft'){e.preventDefault();jump(chapter-1)}});
function makeAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;const ctx=new AC(),master=ctx.createGain(),wind=ctx.createGain(),filter=ctx.createBiquadFilter(),buf=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate);const data=buf.getChannelData(0);let b=0;for(let i=0;i<data.length;i++){b=(b+(.02*(Math.random()*2-1)))/1.02;data[i]=b*5}const noise=ctx.createBufferSource();noise.buffer=buf;noise.loop=true;filter.type='lowpass';filter.frequency.value=450;noise.connect(filter);filter.connect(wind);wind.connect(master);master.connect(ctx.destination);master.gain.value=0;wind.gain.value=.2;noise.start();return {ctx,master,wind,filter}}
function chirp(){if(!audio||!soundOn)return;const {ctx,master}=audio;for(let k=0;k<2;k++){const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+k*.15;o.type='sine';o.frequency.value=k?1350:1000;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.022,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.09);o.connect(g);g.connect(master);o.start(t);o.stop(t+.1)}}
$('sound').onclick=async()=>{try{if(!audio)audio=makeAudio();if(!audio){$('sound').textContent='Sound unavailable';return}await audio.ctx.resume();soundOn=!soundOn;audio.master.gain.setTargetAtTime(soundOn?.55:0,audio.ctx.currentTime,.25);$('sound').textContent=soundOn?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',soundOn);if(soundOn)chirp()}catch(e){$('sound').textContent='Sound unavailable'}};
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();setPlaying(false);$('error').classList.remove('hidden');$('error').textContent='The graphics context was interrupted. Reload this page to restart the diorama.'});
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();updateChapter();
const clearColor=new T.Color('#8aadc4'),nightColor=new T.Color('#081625'),stormColor=new T.Color('#526979'),warmColor=new T.Color('#e5bb95');const world=V(),projected=V();
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.06);last=now;if(document.hidden)return;if(playing){time=Math.min(280,time+dt*speed);if(time>=280)setPlaying(false)}updateChapter();const c=chapters[chapter],next=chapters[Math.min(13,chapter+1)],f=smooth(clamp((time%20)/20,0,1)),u=mix(c.u,next.u,f);let dist=mix(c.dist,next.dist,f),angle=mix(c.angle,next.angle,f),lift=mix(c.lift,next.lift,f);let day=mix(c.day,next.day,f);storm=mix(c.storm,next.storm,f);night=1-day;
// The first and final wide shots blend into the continuous route-following flight.
const routePoint=atRoute(u);targetFocus.copy(routePoint).add(V(0,12,0));if(chapter===0)targetFocus.lerp(V(-15,175,5),1-f);if(chapter>=12){const wide=chapter===13?1:f;targetFocus.lerp(V(-15,175,5),wide)}if(overview){targetFocus.set(-15,175,5);dist=730;angle=-.8;lift=.7}
const damping=needSnap?1:1-Math.exp(-dt*3);focus.lerp(targetFocus,damping);const radius=dist*zoom;desiredCam.set(focus.x+Math.sin(angle+orbit)*radius,focus.y+radius*(lift+pitch),focus.z+Math.cos(angle+orbit)*radius);if(Math.abs(desiredCam.x)<495&&Math.abs(desiredCam.z)<495)desiredCam.y=Math.max(desiredCam.y,height(desiredCam.x,desiredCam.z)+30);camera.position.lerp(desiredCam,damping);camera.lookAt(focus);needSnap=false;
scene.background.copy(nightColor).lerp(clearColor,day).lerp(stormColor,storm*.68);if(day>.25&&day<.7&&storm<.2)scene.background.lerp(warmColor,.12);scene.fog.color.copy(scene.background);scene.fog.density=.0007+storm*.0029;hemi.intensity=.62+day*1.9;sun.intensity=.26+day*2.85;sun.color.set(day<.7?'#e7bba0':'#fff0d7');stars.material.opacity=clamp((night-.45)*1.8,0,1)*(1-storm);snowMat.opacity=storm*.65;flakes.visible=storm>.04;flakes.position.copy(focus);
if(flakes.visible){for(let i=0;i<snowCount;i++){let k=i*3;snowPositions[k]+=dt*(18+storm*70);snowPositions[k+1]-=dt*(7+storm*17);snowPositions[k+2]+=dt*14;if(snowPositions[k]>250)snowPositions[k]=-250;if(snowPositions[k+1]<-180)snowPositions[k+1]=230;if(snowPositions[k+2]>250)snowPositions[k+2]=-250}sg.attributes.position.needsUpdate=true}
flags.forEach((flag,i)=>{flag.rotation.y=Math.sin(now*.003+i*.6)*(.25+storm*.6);flag.rotation.x=Math.sin(now*.004+i)*.16});
const groupU=chapter<5?u:chapter<10?clamp(u,10,15):u;people.forEach((p,i)=>{let pu=groupU-i*.055;if(chapter>=11)pu=10+Math.sin(i*2.4)*.14;pu=clamp(pu,0,15);const v=atRoute(pu),dir=atRoute(clamp(pu+.03,0,15)).sub(v);v.x+=Math.sin(i*8)*1.4;v.z+=Math.cos(i*8)*1.4;v.y=height(v.x,v.z)+.8;p.g.position.copy(v);p.g.rotation.y=Math.atan2(dir.x,dir.z)+(chapter>=10?Math.PI:0);p.g.visible=chapter!==13;p.lamp.visible=day<.6;const walk=playing?Math.sin(now*.005+i)*.25:0;p.legs[0].rotation.x=walk;p.legs[1].rotation.x=-walk});
beacon.position.copy(routePoint).add(V(0,5,0));beacon.visible=chapter<13;beacon.scale.setScalar(1+.12*Math.sin(now*.003));
if(audio){audio.wind.gain.setTargetAtTime(.12+storm*.65+night*.08,audio.ctx.currentTime,.3);audio.filter.frequency.setTargetAtTime(250+storm*1150,audio.ctx.currentTime,.4)}
$('altitude').textContent=Math.round(5000+routePoint.y*10).toLocaleString('en');$('weather').textContent=storm>.65?'SNOW / WHITEOUT':storm>.3?'WIND / LOW VISIBILITY':day<.2?'NIGHT / HEADLAMPS':day<.7?'LOW SUN / HIGH RIDGE':'CLEAR / HIGH MOUNTAIN';$('seek').value=time;$('elapsed').textContent=String(Math.floor(time/60)).padStart(2,'0')+':'+String(Math.floor(time%60)).padStart(2,'0');$('compass').textContent='N '+['↑','↗','→','↘','↓','↙','←','↖'][((Math.round((angle+orbit)*4/Math.PI)%8)+8)%8];
renderer.render(scene,camera);labelClock+=dt;if(labelClock>.07){labelClock=0;const occupied=[];labels.forEach(l=>{projected.copy(l.p).project(camera);const x=(projected.x*.5+.5)*innerWidth,y=(-projected.y*.5+.5)*innerHeight;const near=camera.position.distanceTo(l.p),isClose=l.u>=0&&Math.abs(l.u-u)<1.1;let visible=projected.z<1&&projected.z>-1&&x>50&&x<innerWidth-50&&y>100&&y<innerHeight-150&&(dist>300||isClose||near<210);if(innerWidth<740&&y>innerHeight-395)visible=false;if(visible&&occupied.some(p=>Math.abs(p[0]-x)<135&&Math.abs(p[1]-y)<28))visible=false;l.el.style.display=visible?'block':'none';if(visible){occupied.push([x,y]);l.el.style.left=x+'px';l.el.style.top=y+'px';l.el.classList.toggle('current',isClose)}})}frameCount++;frameTime+=dt;if(frameTime>1){$('fps').textContent=Math.round(frameCount/frameTime)+' FPS';frameCount=0;frameTime=0}}
requestAnimationFrame(frame);
})();
