'use strict';
(()=>{
const T=THREE,D=SG_DATA,$=id=>document.getElementById(id),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let zone='island',selected=null,night=false,moving=!reduced,tourIndex=-1,renderer,scene,camera,active,frameId,last=0,time=0,ready=false,width=1,height=1;
const canvas=$('canvas'),cache=new Map(),ray=new T.Raycaster(),mouse=new T.Vector2(),projection=new T.Vector3();
const cam={yaw:.35,pitch:1.05,distance:185,toYaw:.35,toPitch:1.05,toDistance:185,target:new T.Vector3(),toTarget:new T.Vector3()};
const PAL={ground:0xd4cdb2,side:0x8d9c85,grass:0x9fac78,water:0x78b7b5,road:0x697a75,walk:0xe8dbbf,roof:0xc17353,white:0xf0e6cd,glass:0x709e9e,dark:0x244b4e,tree:0x638e69,leaf:0x8fab79};
const boxGeo=new T.BoxGeometry(1,1,1),cylGeo=new T.CylinderGeometry(1,1,1,10),sphereGeo=new T.IcosahedronGeometry(1,1);
const roofShape=new T.Shape();roofShape.moveTo(-.5,0);roofShape.lineTo(0,.65);roofShape.lineTo(.5,0);roofShape.closePath();const roofGeo=new T.ExtrudeGeometry(roofShape,{depth:1,bevelEnabled:false});roofGeo.translate(0,0,-.5);
const instancedMaterial=new T.MeshLambertMaterial({color:0xffffff});
function batch(){const root=new T.Group(),groups={box:[],cyl:[],ball:[],roof:[]},labels=[],lights=[],pickers=[],actors=[];return {root,groups,labels,lights,pickers,actors,add(kind,x,y,z,sx,sy,sz,c,rot=0){groups[kind].push({x,y,z,sx,sy,sz,c,rot})},finish(){const o=new T.Object3D(),colour=new T.Color();for(const [kind,items]of Object.entries(groups)){if(!items.length)continue;const geo={box:boxGeo,cyl:cylGeo,ball:sphereGeo,roof:roofGeo}[kind];const mesh=new T.InstancedMesh(geo,instancedMaterial,items.length);items.forEach((a,i)=>{o.position.set(a.x,a.y,a.z);o.rotation.set(0,a.rot,0);o.scale.set(a.sx,a.sy,a.sz);o.updateMatrix();mesh.setMatrixAt(i,o.matrix);mesh.setColorAt(i,colour.setHex(a.c))});mesh.instanceMatrix.needsUpdate=true;mesh.instanceColor.needsUpdate=true;root.add(mesh)}return this}}}
function cube(b,x,y,z,w,h,d,c,rot=0){b.add('box',x,y,z,w,h,d,c,rot)}
function cyl(b,x,y,z,r,h,c){b.add('cyl',x,y,z,r,h,r,c)}
function tree(b,x,z,size=1){cyl(b,x,2.1*size,z,.36*size,4.2*size,0x7b6f52);b.add('ball',x,5.3*size,z,2.6*size,2.1*size,2.4*size,PAL.tree);b.add('ball',x+1.1*size,6.0*size,z,1.8*size,1.7*size,1.8*size,PAL.leaf)}
function palm(b,x,z,s=1){cyl(b,x,3.2*s,z,.3*s,6.4*s,0x9d8562);for(let i=0;i<6;i++){let a=i*Math.PI/3;b.add('ball',x+Math.cos(a)*1.8*s,6.2*s,z+Math.sin(a)*1.8*s,2.1*s,.35*s,.75*s,0x618e6b,-a)}}
function ground(b,w=116,d=88){cube(b,0,-2.4,0,w,4.6,d,PAL.side);cube(b,0,.05,0,w,.3,d,PAL.ground);cube(b,0,-4.9,0,w-3,.5,d-3,0x6f8376)}
function road(b,x,z,w,d){cube(b,x,.31,z,w,.2,d,PAL.road);if(w>d){cube(b,x,z===0?.48:.45,z-d/2-.8,w,.3,1.5,PAL.walk);cube(b,x,.45,z+d/2+.8,w,.3,1.5,PAL.walk);for(let k=-w/2+3;k<w/2;k+=7)cube(b,x+k,.44,z,3,.03,.15,0xe8d9a2)}else{cube(b,x-w/2-.8,.45,z,1.5,.3,d,PAL.walk);cube(b,x+w/2+.8,.45,z,1.5,.3,d,PAL.walk);for(let k=-d/2+3;k<d/2;k+=7)cube(b,x,.44,z+k,.15,.03,3,0xe8d9a2)}}
function textMesh(b,label,x,y,z,w=18,colour='#244d49',bg=null,grounded=false){const c=document.createElement('canvas');c.width=1024;c.height=128;const ct=c.getContext('2d');if(bg){ct.fillStyle=bg;ct.fillRect(0,0,c.width,c.height)}ct.font='600 50px Arial';ct.fillStyle=colour;ct.textAlign='center';ct.textBaseline='middle';ct.fillText(label,512,64,970);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const mat=new T.MeshBasicMaterial({map:tex,transparent:!bg,depthWrite:false,side:T.DoubleSide});const m=new T.Mesh(new T.PlaneGeometry(w,w/8),mat);m.position.set(x,y,z);if(grounded)m.rotation.x=-Math.PI/2;b.root.add(m);return m}
function shophouse(b,x,z,w=8,h=10,d=12,c=0xe5d4b4,front=1,sign=null){
 cube(b,x,h/2+.5,z,w-.2,h,d,c);cube(b,x,.9,z+front*(d/2+.8),w,.5,2.2,PAL.walk);cube(b,x,h*.55,z+front*(d/2+.05),w,.32,.3,PAL.white);cube(b,x,h+.5,z+front*d/2,w,.7,.5,PAL.white);b.add('roof',x,h+.8,z,w,.95,d+1,PAL.roof);
 for(let k of[-.27,.27]){cube(b,x+k*w,h*.77,z+front*(d/2+.15),w*.24,2.4,.23,0x416f69);cube(b,x+k*w,h*.77,z+front*(d/2+.28),.12,2.5,.1,PAL.white);for(let yy of[-.7,0,.7])cube(b,x+k*w,h*.77+yy,z+front*(d/2+.32),w*.24,.10,.1,0x92b5a0)}
 for(let k of[-.4,.4])cube(b,x+k*w,2.15,z+front*(d/2+.4),.35,3.5,.4,PAL.white);
 cube(b,x,2.3,z+front*(d/2+.12),w*.65,3.2,.25,PAL.dark);cube(b,x,4.35,z+front*(d/2+1.1),w-.3,.3,2.3,c===0xf4e8cb?0xa5c9a8:0xadc1a1);
 if(sign){const m=textMesh(b,sign,x,3.9,z+front*(d/2+2.28),w-.6,'#254841','#f2e8cd');if(front<0)m.rotation.y=Math.PI}
}
function tower(b,x,z,w,d,h,c=0xc3d1c3){cube(b,x,h/2+.4,z,w,h,d,c);cube(b,x,h+.8,z,w+.4,.6,d+.4,PAL.white);for(let y=3;y<h-1;y+=3){cube(b,x,y,z+d/2+.03,w*.88,1.9,.1,PAL.glass);cube(b,x+w/2+.03,y,z,.1,1.9,d*.85,0x8cb0ac)}for(let k=-w/2+1;k<w/2;k+=2.5)cube(b,x+k,h/2,z+d/2+.12,.25,h,.15,c);cube(b,x,h+1.5,z,w*.4,1.6,d*.4,0xa2b4a7)}
function cafeTables(b,x,z,n=3){for(let i=0;i<n;i++){const xx=x+i*3.4;cyl(b,xx,1.25,z,1.05,.16,0xe2d6b2);cyl(b,xx,.65,z,.13,1.2,0x4c675a);for(let a of[-1,1])cube(b,xx,.7,z+a*1.5,.8,1.25,.8,0x536e5e)}}
function light(b,x,z){cyl(b,x,3,z,.12,6,0x5e7465);cube(b,x,6.1,z,1,.35,.7,0xffedb0);const m=new T.Mesh(new T.SphereGeometry(.25,8,6),new T.MeshBasicMaterial({color:0xffdc91}));m.position.set(x,6.2,z);b.root.add(m);b.lights.push(m)}
function personMesh(colour){const g=new T.Group();const body=new T.Mesh(new T.BoxGeometry(.5,.95,.4),new T.MeshLambertMaterial({color:colour}));body.position.y=1.12;g.add(body);const head=new T.Mesh(new T.SphereGeometry(.26,6,5),new T.MeshLambertMaterial({color:0xccaa87}));head.position.y=1.88;g.add(head);for(let s of[-1,1]){const leg=new T.Mesh(new T.BoxGeometry(.17,.7,.23),new T.MeshLambertMaterial({color:0x385256}));leg.position.set(s*.16,.37,0);g.add(leg)}return g}
function population(b,horizontal=true,offset=0,length=95){for(let i=0;i<10;i++){const g=personMesh([0xd48c69,0x729eb0,0xe8d9b6,0xa1ba8e][i%4]);b.root.add(g);b.actors.push({mesh:g,kind:'walk',offset:offset+(i%2?1:-1)*6.3,length,t:i/10,horizontal,speed:(i%2?1:-1)*.009})}for(let i=0;i<4;i++){const g=new T.Group(),body=new T.Mesh(new T.BoxGeometry(2.1,1.2,4.1),new T.MeshLambertMaterial({color:[0xcbdad0,0xc5a56c,0x376a6d,0xe2beae][i]}));body.position.y=1;g.add(body);const top=new T.Mesh(new T.BoxGeometry(1.8,.75,2.2),new T.MeshLambertMaterial({color:0x72969c}));top.position.y=1.8;g.add(top);if(horizontal)g.rotation.y=Math.PI/2;b.root.add(g);b.actors.push({mesh:g,kind:'car',offset:offset+(i%2?1.7:-1.7),length,t:i/4,horizontal,speed:(i%2?1:-1)*.045})}}
function target(b,p,pinY){const x=p.position[0],z=p.position[2];b.labels.push({id:p.id,pos:new T.Vector3(x,pinY,z),text:p.short,number:p.number});const mesh=new T.Mesh(new T.BoxGeometry(12,pinY,14),new T.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));mesh.position.set(x,pinY/2,z);mesh.userData.place=p.id;b.root.add(mesh);b.pickers.push(mesh);const ring=new T.Mesh(new T.RingGeometry(6.8,7.2,40),new T.MeshBasicMaterial({color:p.colour,transparent:true,opacity:.85,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.64,z);b.root.add(ring);ring.userData.place=p.id;b.actors.push({mesh:ring,kind:'ring',id:p.id})}
function island(){const b=batch();cube(b,0,-5.9,0,270,2,180,0x72aca9);const pts=[[-87,7],[-80,-7],[-66,-18],[-49,-31],[-24,-38],[0,-37],[24,-30],[45,-29],[65,-20],[82,-12],[88,0],[75,12],[62,19],[39,23],[20,28],[1,29],[-14,36],[-32,33],[-49,27],[-65,23],[-78,16]];const shape=new T.Shape();pts.forEach((p,i)=>i?shape.lineTo(p[0],-p[1]):shape.moveTo(p[0],-p[1]));shape.closePath();const geo=new T.ExtrudeGeometry(shape,{depth:3.5,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.8,bevelThickness:.5});geo.rotateX(-Math.PI/2);const land=new T.Mesh(geo,new T.MeshLambertMaterial({color:0xb7c697}));land.position.y=-3.5;b.root.add(land);
 for(let x=-61;x<70;x+=8)for(let z=-8;z<17;z+=7){if((x+z)%3===0)continue;const h=1.5+hash(x,z)*4;cube(b,x,h/2+.5,z,3.4,h,3.2,0xdad8bb)}
 for(let i=0;i<22;i++)tree(b,-40+i*3.1,-21+Math.sin(i*.8)*4,.55);
 for(let x=-63;x<74;x+=5)cube(b,x,.5,17-Math.sin(x*.035)*8,4.1,.08,.7,0x829c82);
 for(let x=-47;x<60;x+=5)cube(b,x,.5,-13+Math.sin(x*.022)*5,4.1,.08,.5,0x93a58b);
 textMesh(b,'S I N G A P O R E',12,.9,-8,61,'#557a5b',null,true);textMesh(b,'JOHOR STRAIT',-13,-4.6,-52,37,'#4a8d89',null,true);textMesh(b,'SINGAPORE STRAIT',0,-4.6,58,43,'#4a8d89',null,true);textMesh(b,'N ↑',101,.6,-40,10,'#2d625b',null,true);
 const pins=[{id:'river',pos:new T.Vector3(-38,7,-5),text:'River & Orchard',number:'01 / 02'},{id:'central',pos:new T.Vector3(-18,7,29),text:'Telok Ayer & Craig',number:'03 / 04'},{id:'katong',pos:new T.Vector3(35,7,12),text:'Katong',number:'05'}];
 for(const p of pins){cyl(b,p.pos.x,2,p.pos.z,1.5,4,0xf2c284);b.labels.push({...p,district:true});const hit=new T.Mesh(new T.SphereGeometry(8,8,6),new T.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));hit.position.copy(p.pos);hit.userData.zone=p.id;b.root.add(hit);b.pickers.push(hit)}
 return b.finish()}
function river(){const b=batch();ground(b);road(b,10,0,10,86);road(b,0,-35,114,7);cube(b,-35,.28,29,43,.15,10,PAL.water);cube(b,-35,.50,22.5,43,.3,2.1,PAL.walk);cube(b,-35,.45,36,43,.3,2.1,PAL.walk);cube(b,-6,.85,29,7,1.5,14,0xd6cfb5);for(let x=-9;x<-2;x+=1.8)cube(b,x,1.8,29,.15,1.3,14,0x728679);
 // Open-sided hawker centre with a deliberately cutaway roof.
 cube(b,-32,.8,16,29,1,13,0xe5d8b7);for(let x=-44;x<=-20;x+=4)for(let z of[10,21])cube(b,x,3,z,.4,4.5,.4,0xd7cba7);
 for(let x=-43;x<=-23;x+=5){cube(b,x,2.5,11,4.4,3,2.2,0x648a7a);cube(b,x,4.2,11.2,4.5,.7,2.5,0xe2be76);cafeTables(b,x,17,1)}
 b.add('roof',-32,5.8,10,30,1.8,5,0xa97652);textMesh(b,'ZION RIVERSIDE',-32,4.8,23.1,23,'#355345','#f5e4b9');
 for(let i=0;i<5;i++)tree(b,-48+i*7,38,.8);for(let i=0;i<4;i++)tree(b,-49+i*10,-7,.8);
 // Orchard's contemporary hotel massing, including a small Level 2 bar cutaway.
 tower(b,29,-22,22,17,29,0xdbd5bd);cube(b,27,3.5,-11.7,23,6,4,0xbaa16b);cube(b,27,4.4,-9.55,18,3,.18,0x365558);cube(b,27,2.9,-8,18,.5,2,0x694e3e);for(let x=20;x<37;x+=3)cyl(b,x,1.6,-6.7,.6,1.1,0x846344);textMesh(b,'MANHATTAN · LEVEL 2',27,6.4,-9.35,21,'#f3d59a','#344b4a');
 for(let x of[15,41])palm(b,x,-8,1);for(let i=0;i<3;i++)tower(b,-40+i*17,-23,11,10,18+i*5,0xbbc9b7);for(let i=0;i<3;i++)tower(b,28+i*11,22,8,10,13+i*3,0xc9d2bd);for(let z=-28;z<32;z+=15){tree(b,1,z,.8);light(b,18,z)}
 textMesh(b,'ZION ROAD',-2,.6,7,17,'#34574b',null,true);textMesh(b,'ORCHARD / CUSCADEN',31,.65,-37,29,'#34574b',null,true);textMesh(b,'ALEXANDRA CANAL',-32,.52,30,28,'#376c67',null,true);population(b,false,10,72);for(const p of D.places.filter(p=>p.zone==='river'))target(b,p,p.id==='manhattan'?34:9);return b.finish()}
function central(){const b=batch();ground(b);road(b,0,0,114,8);road(b,6,0,8,85);const colours=[0xe8dac0,0xb5c5ac,0xe4c5ac,0xf0ddc1,0x9dbaba];
 for(let i=0;i<5;i++){let x=-46+i*8;shophouse(b,x,-14,8,11,15,colours[i],1,x===-22?'MEATSMITH':null)}
 // Meatsmith frontage and pavement tables.
 cube(b,-22,2.7,-5.8,7.6,4.2,.35,0x3d4541);textMesh(b,'MEATSMITH',-22,4.15,-5.5,7.1,'#f8ddbc','#3d4541');cafeTables(b,-28,-3.8,3);
 for(let i=0;i<5;i++){let x=17+i*8;shophouse(b,x,18,8,9.5,15,colours[(i+2)%5],-1,x===25?'BIRDS OF PARADISE':null)}
 textMesh(b,'BIRDS OF PARADISE',25,4.2,9.1,7.5,'#355e4c','#eee8d5').rotation.y=Math.PI;
 for(let i=0;i<4;i++){shophouse(b,-43+i*10,23,9,9,12,colours[i],-1);tower(b,18+i*10,-29,8,9,25+i*7,0xbaccc3)}
 cube(b,42,.5,36,18,.3,10,0x8fa67b);for(let x=36;x<53;x+=5)tree(b,x,35,.9);for(let x=-46;x<53;x+=16){tree(b,x,-5.4,.7);light(b,x,5.9)}
 textMesh(b,'TELOK AYER STREET',-29,.60,1,30,'#efe8ce',null,true);textMesh(b,'CRAIG ROAD',31,.65,5.9,24,'#37554b',null,true);textMesh(b,'CENTRAL SHOPHOUSES',-18,.5,-35,34,'#547567',null,true);population(b,true,0,108);for(const p of D.places.filter(p=>p.zone==='central'))target(b,p,p.id==='meatsmith'?15:13);return b.finish()}
function katong(){const b=batch();ground(b);road(b,0,-3,114,9);road(b,31,0,7,83);const colours=[0xb3c9ad,0xe1b7a2,0xf0dfbb,0x9ebec0,0xe6c89f,0xb7b6ce];
 for(let i=0;i<7;i++){const x=-44+i*9;shophouse(b,x,8,8.8,10+(i%2)*1.5,13,colours[i%6],-1,x===-8?'BIRDS OF PARADISE':null);for(let k of[-.28,.28])cube(b,x+k*8.8,8,1.2,.8,.35,.3,0xf7eacf)}
 for(let i=0;i<8;i++)shophouse(b,-45+i*12,-19,10,12,15,colours[(i+2)%6],1);
 for(let i=0;i<4;i++){shophouse(b,-40+i*16,30,11,9,11,colours[(i+3)%6],-1);tree(b,-33+i*16,20,.85)}
 tower(b,45,22,13,12,25,0xd6dac3);tower(b,47,-27,12,13,20,0xccd4c0);for(let x=-49;x<47;x+=14){palm(b,x,-8.7,.75);light(b,x,3)}cafeTables(b,-17,0,2);
 textMesh(b,'EAST COAST ROAD',-12,.65,-3,39,'#f0e6cb',null,true);textMesh(b,'K A T O N G',-8,.5,40,36,'#487361',null,true);population(b,true,-3,108);target(b,D.places.find(p=>p.id==='bop-katong'),15);return b.finish()}
function hash(x,z){return (Math.sin(x*12.9898+z*78.233)*43758.5453)%1*.5+.5}
function makeZone(id){if(!cache.has(id))cache.set(id,({island,river,central,katong}[id])());return cache.get(id)}
function rebuildPins(){const holder=$('pins');holder.replaceChildren();if(!active)return;for(const p of active.labels){const el=document.createElement('button');el.className='pin'+(p.id===selected?' selected':'');el.innerHTML='<b>'+p.number+'</b>'+p.text;el.setAttribute('aria-label',p.district?'Explore '+p.text:'View '+p.text);el.onclick=()=>p.district?setZone(p.id):selectPlace(p.id);holder.appendChild(el);p.el=el}}
function updatePins(){if(!active)return;for(const p of active.labels){projection.copy(p.pos).project(camera);const x=(projection.x*.5+.5)*width,y=(-projection.y*.5+.5)*height;const off=projection.z>1||projection.z< -1||x<25||x>width-25||y<75||y>height-65;p.el.hidden=off;p.el.style.left=x+'px';p.el.style.top=y+'px';p.el.classList.toggle('selected',p.id===selected)}}
function renderList(){const places=zone==='island'?D.places:D.places.filter(p=>p.zone===zone);$('places').innerHTML='';for(const p of places){const b=document.createElement('button');b.className='place';b.setAttribute('aria-pressed',String(p.id===selected));b.innerHTML='<span class="num">'+p.number+'</span><span><strong>'+p.short+'</strong><small>'+p.type+'</small></span><span class="arrow">↗</span>';b.onclick=()=>selectPlace(p.id);$('places').appendChild(b)}}
function syncZoneUI(){const z=D.zones.find(z=>z.id===zone);$('zoneKicker').textContent=z.kicker;$('zoneTitle').textContent=z.name;$('zoneIntro').textContent=zone==='island'?'Five personal picks. Three neighbourhoods. No sightseeing checklist.':zone==='river'?'Zion by the canal. Manhattan in Orchard.':zone==='central'?'A smokehouse meal. A Craig Road scoop.':'Shophouse colour. Botanical gelato.';for(const b of $('zones').children)b.setAttribute('aria-pressed',String(b.dataset.zone===zone));renderList()}
function homeCamera(){cam.toTarget.set(0,0,0);cam.toYaw=zone==='island'?.10:.38;cam.toPitch=zone==='island'?1.18:.87;cam.toDistance=zone==='island'?210:135;if(width<650)cam.toDistance*=1.12}
function setZone(id,keepSelection=false){if(!D.zones.some(z=>z.id===id))return;zone=id;if(!keepSelection){selected=null;$('browse').hidden=false;$('detail').hidden=true}if(ready){if(active)scene.remove(active.root);active=makeZone(id);scene.add(active.root);rebuildPins();homeCamera();syncLighting()}syncZoneUI();$('status').textContent='Exploring '+D.zones.find(z=>z.id===id).name;renderNeeded=true}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mapLink(p){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.name+' '+p.address)}
function selectPlace(id){const p=D.places.find(p=>p.id===id);if(!p)return;if(zone!==p.zone)setZone(p.zone,true);selected=id;$('browse').hidden=true;$('detail').hidden=false;const pair=D.places.find(x=>x.id===p.pair);
 $('detail').innerHTML='<button class="back-list" id="backList">← All places in this neighbourhood</button><div class="tag">'+esc(p.type)+' / '+esc(p.occasion)+'</div><h2>'+esc(p.name)+'</h2><p class="description">'+esc(p.description)+'</p><div class="personal"><span class="label">'+esc(p.tag)+'</span><p>'+esc(p.note)+'</p></div><div class="section"><h3>Find it</h3><p>'+esc(p.address)+'</p></div><a class="primary" href="'+mapLink(p)+'" target="_blank" rel="noopener noreferrer">Open in Google Maps ↗</a><div class="section"><h3>When to go</h3><p>'+esc(p.hours)+'</p></div><div class="section"><h3>On the menu</h3><p>'+esc(p.order)+'</p></div><div class="section"><h3>Before you go</h3><p>'+esc(p.tip)+'</p></div><div class="section"><h3>Make an outing of it</h3><p>'+esc(p.pairText)+'</p><button class="secondary" id="pair">'+esc(pair.short)+'<span>↗</span></button></div><div class="sources"><a href="'+p.source+'" target="_blank" rel="noopener noreferrer">'+esc(p.sourceLabel)+' ↗</a><a href="'+p.extraSource+'" target="_blank" rel="noopener noreferrer">'+esc(p.extraLabel)+' ↗</a><span class="checked">Details checked '+D.checked+'. Hours and menus may change; this is not live opening status.</span></div>';
 $('backList').onclick=()=>{selected=null;$('browse').hidden=false;$('detail').hidden=true;renderList();homeCamera();renderNeeded=true};$('pair').onclick=()=>selectPlace(p.pair);renderList();if(ready){cam.toTarget.set(p.position[0]*.55,3,p.position[2]*.55);cam.toDistance=width<650?126:110;cam.toPitch=.92;renderNeeded=true}$('sidebar').scrollTop=0;$('status').textContent=p.name+'. '+p.type+'. '+p.address;try{history.replaceState(null,'','#place='+p.id)}catch(e){}
}
let ambient,sun,renderNeeded=true;
function syncLighting(){if(!ready)return;document.body.classList.toggle('theme-night',night);scene.background.set(night?0x132d3b:0xb5d8d0);scene.fog.color.copy(scene.background);ambient.intensity=night?.85:2.1;sun.intensity=night?.6:2.1;sun.color.set(night?0xbad4e0:0xffedc4);instancedMaterial.color.set(night?0xb6c6bc:0xffffff);for(const b of cache.values())for(const l of b.lights)l.visible=night;$('lighting').textContent=night?'AM':'PM';$('lighting').setAttribute('aria-pressed',String(night));$('lighting').setAttribute('aria-label',night?'Switch to daytime lighting':'Switch to evening lighting');renderNeeded=true}
function updateActors(dt){if(!active)return;for(const a of active.actors){if(a.kind==='ring'){a.mesh.material.opacity=a.id===selected?.9:.4;continue}if(moving){a.t=(a.t+dt*a.speed+1)%1}const pos=(a.t-.5)*a.length;if(a.horizontal)a.mesh.position.set(pos,0,a.offset);else a.mesh.position.set(a.offset,0,pos);if(a.kind==='walk'){a.mesh.rotation.y=a.horizontal?(a.speed>0?Math.PI/2:-Math.PI/2):(a.speed>0?0:Math.PI);a.mesh.children[2].rotation.x=Math.sin(time*9+a.t*20)*.35;a.mesh.children[3].rotation.x=-Math.sin(time*9+a.t*20)*.35}}}
function resize(){const r=$('world').getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);if(ready){renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();renderNeeded=true}}
function tick(now){frameId=requestAnimationFrame(tick);if(document.hidden){last=now;return}const dt=Math.min(.05,(now-last)/1000||0);last=now;if(moving)time+=dt;const k=reduced?1:1-Math.exp(-dt*6);let unsettled=Math.abs(cam.yaw-cam.toYaw)+Math.abs(cam.pitch-cam.toPitch)+Math.abs(cam.distance-cam.toDistance)+cam.target.distanceTo(cam.toTarget)>.002;cam.yaw+=(cam.toYaw-cam.yaw)*k;cam.pitch+=(cam.toPitch-cam.pitch)*k;cam.distance+=(cam.toDistance-cam.distance)*k;cam.target.lerp(cam.toTarget,k);camera.position.set(cam.target.x+Math.sin(cam.yaw)*Math.cos(cam.pitch)*cam.distance,cam.target.y+Math.sin(cam.pitch)*cam.distance,cam.target.z+Math.cos(cam.yaw)*Math.cos(cam.pitch)*cam.distance);camera.lookAt(cam.target);camera.updateMatrixWorld();if(moving||unsettled||renderNeeded){updateActors(dt);updatePins();renderer.render(scene,camera);renderNeeded=false}}
const points=new Map();let gesture=null;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});gesture={x:e.clientX,y:e.clientY,moved:false};});
canvas.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;const p=points.get(e.pointerId),dx=e.clientX-p.x,dy=e.clientY-p.y;const before=[...points.values()];points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(gesture&&Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>5)gesture.moved=true;if(points.size===2){const after=[...points.values()],a=Math.hypot(before[0].x-before[1].x,before[0].y-before[1].y),b=Math.hypot(after[0].x-after[1].x,after[0].y-after[1].y);if(b>1)cam.toDistance=clamp(cam.toDistance*a/b,65,300)}else{cam.toYaw-=dx*.007;cam.toPitch=clamp(cam.toPitch+dy*.005,.35,1.48)}renderNeeded=true});
canvas.addEventListener('pointerup',e=>{const wasMulti=points.size>1;points.delete(e.pointerId);if(gesture&&!gesture.moved&&!wasMulti&&ready){const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(active.pickers)[0];if(hit){if(hit.object.userData.zone)setZone(hit.object.userData.zone);else selectPlace(hit.object.userData.place)}}gesture=null});canvas.addEventListener('pointercancel',e=>{points.delete(e.pointerId);gesture=null});canvas.addEventListener('wheel',e=>{e.preventDefault();cam.toDistance=clamp(cam.toDistance*Math.exp(e.deltaY*.001),65,300);renderNeeded=true},{passive:false});
canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')cam.toYaw-=.14;if(e.key==='ArrowRight')cam.toYaw+=.14;if(e.key==='ArrowUp')cam.toPitch=clamp(cam.toPitch+.1,.35,1.48);if(e.key==='ArrowDown')cam.toPitch=clamp(cam.toPitch-.1,.35,1.48);if(e.key==='+')cam.toDistance=clamp(cam.toDistance*.85,65,300);if(e.key==='-')cam.toDistance=clamp(cam.toDistance/ .85,65,300);if(e.key==='Home')homeCamera();renderNeeded=true});
$('zoomIn').onclick=()=>{cam.toDistance=clamp(cam.toDistance*.82,65,300);renderNeeded=true};$('zoomOut').onclick=()=>{cam.toDistance=clamp(cam.toDistance/ .82,65,300);renderNeeded=true};$('reset').onclick=()=>{homeCamera();renderNeeded=true};$('lighting').onclick=()=>{night=!night;syncLighting()};$('motion').setAttribute('aria-pressed',String(moving));$('motion').textContent=moving?'Ⅱ':'▶';$('motion').onclick=()=>{moving=!moving;$('motion').textContent=moving?'Ⅱ':'▶';$('motion').setAttribute('aria-pressed',String(moving));renderNeeded=true};
function tourStep(){const order=['zion','manhattan','meatsmith','bop-craig','bop-katong'],p=D.places.find(p=>p.id===order[tourIndex]);selectPlace(p.id);$('tour').hidden=false;$('tourCount').textContent=(tourIndex+1)+' / 5 PLACES';$('tourTitle').textContent=p.short;$('tourCopy').textContent=p.occasion+' · '+p.type+'. Explore the scene, then move on when you’re ready.';$('tourNext').textContent=tourIndex===4?'Back to the island':'Next place →'}
$('tourStart').onclick=()=>{tourIndex=0;tourStep()};$('tourNext').onclick=()=>{if(tourIndex===4){tourIndex=-1;$('tour').hidden=true;setZone('island')}else{tourIndex++;tourStep()}};$('tourStop').onclick=()=>{tourIndex=-1;$('tour').hidden=true};$('dismissError').onclick=()=>$('error').hidden=true;
for(const z of D.zones){const b=document.createElement('button');b.textContent=z.short;b.dataset.zone=z.id;b.setAttribute('aria-pressed',String(z.id==='island'));b.onclick=()=>{tourIndex=-1;$('tour').hidden=true;setZone(z.id)};$('zones').appendChild(b)}syncZoneUI();
try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(0xb5d8d0);scene=new T.Scene();scene.background=new T.Color(0xb5d8d0);scene.fog=new T.Fog(0xb5d8d0,220,500);ambient=new T.HemisphereLight(0xe2f3ec,0x819586,2.1);scene.add(ambient);sun=new T.DirectionalLight(0xffedc4,2.1);sun.position.set(-55,100,50);scene.add(sun);camera=new T.PerspectiveCamera(43,1,.1,650);ready=true;resize();setZone('island');cam.yaw=cam.toYaw;cam.pitch=cam.toPitch;cam.distance=cam.toDistance;new ResizeObserver(resize).observe($('world'));$('loading').hidden=true;requestAnimationFrame(tick);const id=new URLSearchParams(location.hash.slice(1)).get('place');if(id)selectPlace(id)}catch(e){console.error(e);$('loading').hidden=true;$('error').hidden=false;$('status').textContent='3D unavailable. The place guide remains available.'}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;cancelAnimationFrame(frameId);$('error').hidden=false;$('error').querySelector('h2').textContent='The 3D view was interrupted.'});
window.SGExplorer={setZone,selectPlace,getStats:()=>({zone,selected,places:D.places.length,cachedScenes:cache.size,instances:[...cache.values()].reduce((n,b)=>n+Object.values(b.groups).reduce((a,g)=>a+g.length,0),0),ready}),mapLink};
})();
