window.SG_DATA={
  "checked": "6 September 2026",
  "zones": [
    {
      "id": "island",
      "name": "Singapore",
      "short": "Island overview",
      "kicker": "THE WHOLE PICTURE",
      "description": "Ten food stops across six neighbourhoods. Pick a colourful district and step into its streets.",
      "colour": "#67d3bc",
      "count": 10,
      "intro": "Ten food stops. Six neighbourhoods. Pick a pin and wander."
    },
    {
      "id": "river",
      "name": "River Valley & Orchard",
      "short": "River & Orchard",
      "kicker": "01 / HAWKER TABLES TO COCKTAILS",
      "description": "Two very different stops: Zion by the canal, Manhattan up in Orchard. They are separate outings or a ride apart, not neighbouring doors.",
      "colour": "#e9b466",
      "count": 2,
      "intro": "Hawker tables by the canal. Cocktails in Orchard."
    },
    {
      "id": "central",
      "name": "Telok Ayer & Craig Road",
      "short": "Telok Ayer & Craig",
      "kicker": "02 / SMOKE, SHOPHOUSES & A SCOOP",
      "description": "Meatsmith is the anchor. Craig Road is the dessert detour. The model brings two central streets together; use directions for the actual walk.",
      "colour": "#f49a7b",
      "count": 2,
      "intro": "A smokehouse meal. A Craig Road scoop."
    },
    {
      "id": "katong",
      "name": "Katong",
      "short": "Katong",
      "kicker": "03 / TAKE THE AFTERNOON EAST",
      "description": "A slower pocket of shophouses and side streets, centred on Andrew’s Birds of Paradise pick on East Coast Road.",
      "colour": "#98cbd9",
      "count": 1,
      "intro": "Shophouse colour. Botanical gelato."
    },
    {
      "id": "tiong",
      "name": "Tiong Bahru",
      "short": "Tiong Bahru",
      "kicker": "04 / MARKET MORNINGS & DECO STREETS",
      "description": "A market meal, then a slow wander around the estate’s low-rise Art Deco streets.",
      "intro": "Market tables, curved corners and leafy backstreets.",
      "colour": "#ffcc55",
      "count": 1
    },
    {
      "id": "india",
      "name": "Little India",
      "short": "Little India",
      "kicker": "05 / RACE COURSE ROAD",
      "description": "Two of Andrew’s picks on Race Course Road: The Banana Leaf Apolo and Jaggi’s.",
      "intro": "Banana-leaf meals and Punjabi cooking on Race Course Road.",
      "colour": "#dba5ff",
      "count": 2
    },
    {
      "id": "golden",
      "name": "Golden Mile Thai trail",
      "short": "Golden Mile Thai",
      "kicker": "06 / FAMILIAR FLAVOURS, NEW ADDRESSES",
      "description": "Golden Mile Complex’s Thai food community moved out in 2023. Follow it to City Gate and Aperia; these are separate stops.",
      "intro": "The old food scene lives on around Beach Road and Lavender.",
      "colour": "#ff9173",
      "count": 2
    }
  ],
  "places": [
    {
      "id": "zion",
      "number": "01",
      "zone": "river",
      "name": "Zion Riverside Food Centre",
      "short": "Zion Riverside",
      "type": "Hawker food",
      "occasion": "Casual lunch",
      "tag": "Andrew’s pick",
      "note": "One of Andrew’s starting recommendations for this collection.",
      "description": "A hawker food stop beside Alexandra Canal. Come for a meal and choose from the stalls that are trading that day.",
      "address": "70 Zion Road, Singapore 247792",
      "hours": "Hours vary by stall. Check stall opening days and NEA cleaning closures before a special trip.",
      "order": "Choose your stall on arrival. Andrew’s specific stall and dish picks are still to come.",
      "tip": "This is an everyday food-centre stop. The miniature’s open roof lets you look inside; it is not a surveyed model.",
      "position": [
        -32,
        0,
        16
      ],
      "mapPosition": [
        -25,
        0,
        13
      ],
      "source": "https://www.nea.gov.sg/docs/default-source/hawker-centres-documents/list-of-hcs_-17-august-2026.pdf",
      "sourceLabel": "NEA centre directory",
      "extraSource": "https://www.nea.gov.sg/our-services/hawker-management/overview",
      "extraLabel": "Check cleaning closures",
      "pair": "manhattan",
      "pairText": "Another pick in the wider area: Manhattan. Plan a separate evening visit or a ride between the two.",
      "colour": 15316070
    },
    {
      "id": "manhattan",
      "number": "02",
      "zone": "river",
      "name": "Manhattan",
      "short": "Manhattan",
      "type": "Cocktail bar",
      "occasion": "An evening out",
      "tag": "Andrew’s pick",
      "note": "Selected by Andrew for the opening collection.",
      "description": "The cocktail stop at Conrad Singapore Orchard, on Level 2. A dress-up-a-little evening rather than a hawker-centre pit stop.",
      "address": "Level 2, Conrad Singapore Orchard, 1 Cuscaden Road, Singapore 249715",
      "hours": "Sun–Thu 5 pm–midnight; Fri–Sat 5 pm–1 am.",
      "order": "The bar’s published signatures include the Barrel-Aged Manhattan and Solera-Aged Negroni. These are menu ideas, not Andrew’s personal order.",
      "tip": "Smart casual; closed-toe footwear for gentlemen. The hotel excludes slippers, flip-flops and activewear. Check reservations and current menus with the venue.",
      "position": [
        27,
        0,
        -20
      ],
      "mapPosition": [
        -33,
        0,
        5
      ],
      "source": "https://www.hilton.com/en/hotels/sinodci-conrad-singapore-orchard/dining/manhattan/",
      "sourceLabel": "Official hours, dress code & menu",
      "extraSource": "https://www.hilton.com/en/hotels/sinodci-conrad-singapore-orchard/",
      "extraLabel": "Hotel address",
      "pair": "zion",
      "pairText": "For a different part of the day: Zion Riverside Food Centre. They are separate stops, not a single street.",
      "colour": 14269571
    },
    {
      "id": "meatsmith",
      "number": "03",
      "zone": "central",
      "name": "Meatsmith Telok Ayer",
      "short": "Meatsmith",
      "type": "Smokehouse",
      "occasion": "Lunch or dinner",
      "tag": "Andrew’s favourite",
      "note": "“That’s a fav.” — Andrew, on Meatsmith Telok Ayer.",
      "description": "An American-style smokehouse on Telok Ayer Street. This is the meal to build the central neighbourhood visit around.",
      "address": "167 Telok Ayer Street, Singapore 068618",
      "hours": "Daily 11:30 am–10:30 pm. Kitchen closes at 10 pm.",
      "order": "Beef brisket, ribs or a burger are starting points from the venue’s menu. Andrew’s exact go-to order is still to come.",
      "tip": "The venue recommends reserving for weekends and groups of four or more. Telok Ayer and Tanjong Pagar are its listed MRT options.",
      "position": [
        -22,
        0,
        -14
      ],
      "mapPosition": [
        -20,
        0,
        22
      ],
      "source": "https://meatsmith.com.sg/reservation/",
      "sourceLabel": "Official address, hours & reservations",
      "extraSource": "https://meatsmith.com.sg/",
      "extraLabel": "Current menu & signatures",
      "pair": "bop-craig",
      "pairText": "Make dessert a separate stop at Birds of Paradise, Craig Road. Check the walking route rather than following this compressed model.",
      "colour": 16030331
    },
    {
      "id": "bop-craig",
      "number": "04",
      "zone": "central",
      "name": "Birds of Paradise · Craig Road",
      "short": "BOP · Craig",
      "type": "Botanical gelato",
      "occasion": "Dessert detour",
      "tag": "Andrew-approved branch",
      "note": "Andrew recommends both the Craig Road and Katong branches.",
      "description": "The central-city branch of Andrew’s gelato pick, tucked into Craig Road’s shophouse neighbourhood.",
      "address": "53 Craig Road #01-01, Singapore 089691",
      "hours": "Sun–Thu noon–10 pm; Fri–Sat noon–10:30 pm.",
      "order": "Botanical gelato and a thyme cone. White Chrysanthemum is one published flavour to look for; daily availability can vary.",
      "tip": "Pair this branch with a central-city meal. Choose Katong when your day is already out east; there is no need to visit both in one outing.",
      "position": [
        25,
        0,
        18
      ],
      "mapPosition": [
        -24,
        0,
        26
      ],
      "source": "https://birdsofparadise.sg/pages/boutiques",
      "sourceLabel": "Official branches, menus & hours",
      "extraSource": "https://birdsofparadise.sg/",
      "extraLabel": "Flavours & thyme cones",
      "pair": "meatsmith",
      "pairText": "Start with Meatsmith Telok Ayer, then check the walk to Craig Road for dessert.",
      "colour": 9164218
    },
    {
      "id": "bop-katong",
      "number": "05",
      "zone": "katong",
      "name": "Birds of Paradise · Katong",
      "short": "BOP · Katong",
      "type": "Botanical gelato",
      "occasion": "An afternoon east",
      "tag": "Andrew-approved branch",
      "note": "Andrew recommends both the Katong and Craig Road branches.",
      "description": "Andrew’s East Coast Road gelato stop, in the Katong shophouse neighbourhood.",
      "address": "63 East Coast Road #01-05, Singapore 428776",
      "hours": "Sun–Thu noon–10 pm; Fri–Sat noon–10:30 pm.",
      "order": "Choose a botanical flavour and a thyme cone. White Chrysanthemum is a venue-listed option, not a claimed favourite of Andrew’s.",
      "tip": "Use this as the anchor for a relaxed Katong wander. More of Andrew’s east-side stops can be added around it over time.",
      "position": [
        -8,
        0,
        8
      ],
      "mapPosition": [
        31,
        0,
        9
      ],
      "source": "https://birdsofparadise.sg/pages/boutiques",
      "sourceLabel": "Official branches, menus & hours",
      "extraSource": "https://birdsofparadise.sg/",
      "extraLabel": "Flavours & thyme cones",
      "pair": "bop-craig",
      "pairText": "Staying central instead? Craig Road is the other Andrew-approved branch.",
      "colour": 10013657
    },
    {
      "tag": "Andrew’s pick",
      "note": "Andrew recommends the market for local flavour and the surrounding Art Deco houses.",
      "sourceLabel": "NEA market directory",
      "extraLabel": "National Heritage Board: architecture",
      "colour": 16763989,
      "id": "tiong-market",
      "number": "06",
      "zone": "tiong",
      "name": "Tiong Bahru Market",
      "short": "Tiong Bahru Market",
      "type": "Hawker food & heritage streets",
      "occasion": "A morning wander",
      "description": "A meal at the market, followed by a wander around the low-rise estate. Look for rounded corners, long horizontal lines and deep window shades.",
      "address": "30 Seng Poh Road, Singapore 168898",
      "hours": "Morning or lunch makes a good starting plan. Stall hours differ; check NEA cleaning closures before a special trip.",
      "order": "Browse the stalls that are trading. Andrew’s individual stall and dish recommendations are still to come.",
      "tip": "The surrounding homes are lived in: keep to public streets and paths. Tiong Bahru’s pre-war blocks draw on Streamline Moderne, part of the Art Deco family.",
      "position": [
        -23,
        0,
        -13
      ],
      "source": "https://www.nea.gov.sg/docs/default-source/hawker-centres-documents/list-of-hcs_-17-august-2026.pdf",
      "extraSource": "https://www.roots.gov.sg/places/places-landing/Places/landmarks/tiong-bahru-heritage-trail/the-architecture-of-tiong-bahru",
      "pair": "zion",
      "pairText": "Another hawker outing in this part of Singapore: Zion Riverside. Use the map to plan the route."
    },
    {
      "tag": "Andrew’s pick",
      "note": "Recommended by Andrew for this collection.",
      "sourceLabel": "Official venue details",
      "extraLabel": "Signatures & contact details",
      "colour": 14394879,
      "id": "apolo",
      "number": "07",
      "zone": "india",
      "name": "The Banana Leaf Apolo",
      "short": "Banana Leaf Apolo",
      "type": "Indian food",
      "occasion": "Lunch or dinner",
      "description": "Andrew’s banana-leaf meal stop on Race Course Road. The restaurant’s published signatures span fish head curry, briyani and tandoori dishes.",
      "address": "54 Race Course Road, Singapore 218564",
      "hours": "Daily 10:30 am–10:30 pm, according to the restaurant.",
      "order": "Fish head curry, mutton briyani or a vegetarian meal are venue-listed ideas. Andrew’s usual order is still to come.",
      "tip": "This card is for the Race Course Road restaurant. Check the current menu and availability directly before a special trip.",
      "position": [
        -26,
        0,
        -14
      ],
      "source": "https://www.thebananaleafapolo.com/",
      "extraSource": "https://www.thebananaleafapolo.com/",
      "pair": "jaggis",
      "pairText": "Jaggi’s is Andrew’s other Race Course Road suggestion. Choose one for this meal and save the other for another visit."
    },
    {
      "tag": "Andrew’s pick",
      "note": "Recommended by Andrew for this collection.",
      "sourceLabel": "Current official address",
      "extraLabel": "Contact details (older address listed)",
      "colour": 14394879,
      "id": "jaggis",
      "number": "08",
      "zone": "india",
      "name": "Jaggi’s Northern Indian Cuisine",
      "short": "Jaggi’s",
      "type": "Punjabi food",
      "occasion": "Lunch or dinner",
      "description": "Andrew’s North Indian option on Race Course Road, with Punjabi cooking at the heart of the menu.",
      "address": "72 Race Course Road, Singapore 218573",
      "hours": "The published contact page lists 11 am–10:30 pm, but has an older street number. Confirm current hours on +65 6296 6141.",
      "order": "Explore the Punjabi menu at the counter or through the venue. Andrew’s particular dishes are still to come.",
      "tip": "The current homepage lists 72 Race Course Road. An older contact page still says 36; the map link uses 72. Call the venue if planning a special trip.",
      "position": [
        10,
        0,
        -14
      ],
      "source": "https://jaggis.com.sg/",
      "extraSource": "https://jaggis.com.sg/contact/",
      "pair": "apolo",
      "pairText": "The Banana Leaf Apolo is Andrew’s other recommendation along Race Course Road."
    },
    {
      "tag": "Golden Mile trail · suggested stop",
      "note": "Andrew recommended the Golden Mile Thai scene. This is a researched starting point; his exact restaurant favourites are still to come.",
      "sourceLabel": "Official location & hours",
      "extraLabel": "Where the Golden Mile eateries moved",
      "colour": 16748915,
      "id": "diandin",
      "number": "09",
      "zone": "golden",
      "name": "Diandin Leluk · City Gate",
      "short": "Diandin Leluk",
      "type": "Thai food",
      "occasion": "Lunch or dinner",
      "description": "An old Golden Mile Complex name, now at City Gate on Beach Road. A current address for exploring the Thai food scene Andrew remembers.",
      "address": "371 Beach Road, City Gate #01-17/18, Singapore 199597",
      "hours": "Daily 10 am–10 pm, according to the venue.",
      "order": "Browse the Thai menu for a shared meal. Papaya salad and mango sticky rice are listed options, not claimed personal favourites.",
      "tip": "Go to City Gate, not the former Golden Mile Complex address. The old complex’s food tenants moved out in 2023.",
      "position": [
        -27,
        0,
        17
      ],
      "source": "https://diandinleluk.com.sg/contact/",
      "extraSource": "https://cnalifestyle.channelnewsasia.com/dining/golden-mile-complex-restaurants-supermarket-new-address-352971",
      "pair": "im-em",
      "pairText": "Another former Golden Mile eatery is Im-Em at Aperia. It is a separate stop: use Maps for the actual route."
    },
    {
      "tag": "Golden Mile trail · suggested stop",
      "note": "A second researched stop for Andrew’s Golden Mile Thai theme. His specific Thai restaurant favourites have not yet been named.",
      "sourceLabel": "Aperia landlord’s tenant directory",
      "extraLabel": "Restaurant updates",
      "colour": 16748915,
      "id": "im-em",
      "number": "10",
      "zone": "golden",
      "name": "Im-Em Thai Kitchen · Aperia",
      "short": "Im-Em Thai Kitchen",
      "type": "Thai food",
      "occasion": "Lunch or dinner",
      "description": "Formerly Dee Tongue Thai at Golden Mile Complex, now Im-Em Thai Kitchen at Aperia in the Lavender area.",
      "address": "12 Kallang Avenue, Aperia Mall #01-40, Singapore 339511",
      "hours": "Check the restaurant’s latest hours before a special trip; published listings differ on the morning opening time.",
      "order": "Choose from the Thai menu when you arrive. Andrew’s personal dish picks are still to come.",
      "tip": "The destination is Aperia, not Golden Mile Complex. The model compresses Beach Road and Lavender into one scene; follow the map for directions.",
      "position": [
        28,
        0,
        -18
      ],
      "source": "https://www.capitaland.com/sg/en/shop/malls/stores/im-em-thai-kitchen.html",
      "extraSource": "https://www.facebook.com/deetonguethai/",
      "pair": "diandin",
      "pairText": "For a Beach Road option instead, Diandin Leluk is at City Gate."
    }
  ]
};
