window.SG_DATA={
 checked:'6 September 2026',
 zones:[
 {id:'island',name:'Singapore',short:'Island overview',kicker:'THE WHOLE PICTURE',description:'Five places Andrew would send a mate. Choose a neighbourhood to step into its miniature streets.',colour:'#67d3bc',count:5},
 {id:'river',name:'River Valley & Orchard',short:'River & Orchard',kicker:'01 / HAWKER TABLES TO COCKTAILS',description:'Two very different stops: Zion by the canal, Manhattan up in Orchard. They are separate outings or a ride apart, not neighbouring doors.',colour:'#e9b466',count:2},
 {id:'central',name:'Telok Ayer & Craig Road',short:'Telok Ayer & Craig',kicker:'02 / SMOKE, SHOPHOUSES & A SCOOP',description:'Meatsmith is the anchor. Craig Road is the dessert detour. The model brings two central streets together; use directions for the actual walk.',colour:'#f49a7b',count:2},
 {id:'katong',name:'Katong',short:'Katong',kicker:'03 / TAKE THE AFTERNOON EAST',description:'A slower pocket of shophouses and side streets, centred on Andrew’s Birds of Paradise pick on East Coast Road.',colour:'#98cbd9',count:1}
 ],
 places:[
 {id:'zion',number:'01',zone:'river',name:'Zion Riverside Food Centre',short:'Zion Riverside',type:'Hawker food',occasion:'Casual lunch',tag:'Andrew’s pick',note:'One of Andrew’s starting recommendations for this collection.',description:'A hawker food stop beside Alexandra Canal. Come for a meal and choose from the stalls that are trading that day.',address:'70 Zion Road, Singapore 247792',hours:'Hours vary by stall. Check stall opening days and NEA cleaning closures before a special trip.',order:'Choose your stall on arrival. Andrew’s specific stall and dish picks are still to come.',tip:'This is an everyday food-centre stop. The miniature’s open roof lets you look inside; it is not a surveyed model.',position:[-32,0,16],mapPosition:[-25,0,13],source:'https://www.nea.gov.sg/docs/default-source/hawker-centres-documents/list-of-hcs_-23-july-2026.pdf',sourceLabel:'NEA centre directory',extraSource:'https://www.nea.gov.sg/our-services/hawker-management/overview',extraLabel:'Check cleaning closures',pair:'manhattan',pairText:'Another pick in the wider area: Manhattan. Plan a separate evening visit or a ride between the two.',colour:0xe9b466},
 {id:'manhattan',number:'02',zone:'river',name:'Manhattan',short:'Manhattan',type:'Cocktail bar',occasion:'An evening out',tag:'Andrew’s pick',note:'Selected by Andrew for the opening collection.',description:'The cocktail stop at Conrad Singapore Orchard, on Level 2. A dress-up-a-little evening rather than a hawker-centre pit stop.',address:'Level 2, Conrad Singapore Orchard, 1 Cuscaden Road, Singapore 249715',hours:'Sun–Thu 5 pm–midnight; Fri–Sat 5 pm–1 am.',order:'The bar’s published signatures include the Barrel-Aged Manhattan and Solera-Aged Negroni. These are menu ideas, not Andrew’s personal order.',tip:'Smart casual; closed-toe footwear for gentlemen. The hotel excludes slippers, flip-flops and activewear. Check reservations and current menus with the venue.',position:[27,0,-20],mapPosition:[-33,0,5],source:'https://www.hilton.com/en/hotels/sinodci-conrad-singapore-orchard/dining/manhattan/',sourceLabel:'Official hours, dress code & menu',extraSource:'https://www.hilton.com/en/hotels/sinodci-conrad-singapore-orchard/',extraLabel:'Hotel address',pair:'zion',pairText:'For a different part of the day: Zion Riverside Food Centre. They are separate stops, not a single street.',colour:0xd9bc83},
 {id:'meatsmith',number:'03',zone:'central',name:'Meatsmith Telok Ayer',short:'Meatsmith',type:'Smokehouse',occasion:'Lunch or dinner',tag:'Andrew’s favourite',note:'“That’s a fav.” — Andrew, on Meatsmith Telok Ayer.',description:'An American-style smokehouse on Telok Ayer Street. This is the meal to build the central neighbourhood visit around.',address:'167 Telok Ayer Street, Singapore 068618',hours:'Daily 11:30 am–10:30 pm. Kitchen closes at 10 pm.',order:'Beef brisket, ribs or a burger are starting points from the venue’s menu. Andrew’s exact go-to order is still to come.',tip:'The venue recommends reserving for weekends and groups of four or more. Telok Ayer and Tanjong Pagar are its listed MRT options.',position:[-22,0,-14],mapPosition:[-20,0,22],source:'https://meatsmith.com.sg/reservation/',sourceLabel:'Official address, hours & reservations',extraSource:'https://meatsmith.com.sg/',extraLabel:'Current menu & signatures',pair:'bop-craig',pairText:'Make dessert a separate stop at Birds of Paradise, Craig Road. Check the walking route rather than following this compressed model.',colour:0xf49a7b},
 {id:'bop-craig',number:'04',zone:'central',name:'Birds of Paradise · Craig Road',short:'BOP · Craig',type:'Botanical gelato',occasion:'Dessert detour',tag:'Andrew-approved branch',note:'Andrew recommends both the Craig Road and Katong branches.',description:'The central-city branch of Andrew’s gelato pick, tucked into Craig Road’s shophouse neighbourhood.',address:'53 Craig Road #01-01, Singapore 089691',hours:'Sun–Thu noon–10 pm; Fri–Sat noon–10:30 pm.',order:'Botanical gelato and a thyme cone. White Chrysanthemum is one published flavour to look for; daily availability can vary.',tip:'Pair this branch with a central-city meal. Choose Katong when your day is already out east; there is no need to visit both in one outing.',position:[25,0,18],mapPosition:[-24,0,26],source:'https://birdsofparadise.sg/pages/boutiques',sourceLabel:'Official branches, menus & hours',extraSource:'https://birdsofparadise.sg/',extraLabel:'Flavours & thyme cones',pair:'meatsmith',pairText:'Start with Meatsmith Telok Ayer, then check the walk to Craig Road for dessert.',colour:0x8bd5ba},
 {id:'bop-katong',number:'05',zone:'katong',name:'Birds of Paradise · Katong',short:'BOP · Katong',type:'Botanical gelato',occasion:'An afternoon east',tag:'Andrew-approved branch',note:'Andrew recommends both the Katong and Craig Road branches.',description:'Andrew’s East Coast Road gelato stop, in the Katong shophouse neighbourhood.',address:'63 East Coast Road #01-05, Singapore 428776',hours:'Sun–Thu noon–10 pm; Fri–Sat noon–10:30 pm.',order:'Choose a botanical flavour and a thyme cone. White Chrysanthemum is a venue-listed option, not a claimed favourite of Andrew’s.',tip:'Use this as the anchor for a relaxed Katong wander. More of Andrew’s east-side stops can be added around it over time.',position:[-8,0,8],mapPosition:[31,0,9],source:'https://birdsofparadise.sg/pages/boutiques',sourceLabel:'Official branches, menus & hours',extraSource:'https://birdsofparadise.sg/',extraLabel:'Flavours & thyme cones',pair:'bop-craig',pairText:'Staying central instead? Craig Road is the other Andrew-approved branch.',colour:0x98cbd9}
 ]
};
